version: "3.8"

services:
  webserver1:
    image: webserver:latest
    container_name: webserver1
    user: 1000:1000
    environment:
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
      - APPNAME=webserver1
    ports:
      - "8081:8080"
    volumes:
      - ./logs:/logs
    depends_on:
      - redis-dev

  webserver2:
    image: webserver:latest
    container_name: webserver2
    user: 1000:1000
    environment:
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
      - APPNAME=webserver2
    ports:
      - "8082:8080"
    volumes:
      - ./logs:/logs
    depends_on:
      - redis-dev

  # NGINX as reverse proxy
  nginx-dev:
    image: nginx:alpine
    container_name: nginx-dev
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "8089:8089"
    depends_on:
      - webserver1
      - webserver2

  redis-dev:
    image: redis:alpine
    container_name: redis-dev
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge
