version: "3.8"

services:
  webserver1:
    image: webserver:latest
    container_name: webserver1
    environment:
      - REDIS_HOST=redis-dev
    ports:
      - "8081:8080"
    depends_on:
      - redis-dev

  webserver2:
    image: webserver:latest
    container_name: webserver2
    environment:
      - REDIS_HOST=redis-dev
    ports:
      - "8082:8080"
    depends_on:
      - redis-dev

  # NGINX as reverse proxy
  nginx-dev:
    image: nginx:alpine
    container_name: nginx-dev
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - webserver1
      - webserver2

  # Redis for caching
  redis-dev:
    image: redis:alpine
    container_name: redis-dev
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge
